spring: 
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      
  datasource: 
    url: jdbc:postgresql://localhost:5432/Vuelos
    platform: postgres
    username: postgres
    password: 1234
 
jwt:
  expires_in: 600
  secret: queenvictoria